[package]
name = "client"
description = "CMP standard game client"
version.workspace = true
edition.workspace = true

[dependencies]
cmp = { path = "../cmp" }
bevy = { git = "https://github.com/bevyengine/bevy", rev = "e3a59c4", features = ["dynamic_linking"] }
